// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://opealgxzsogetdhqkwnl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9wZWFsZ3h6c29nZXRkaHFrd25sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDk4NDksImV4cCI6MjA2NTI4NTg0OX0.-DkPYzgc3xDD3uDE7PoHbLviA8q8YO3D9d3jNFLIXVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);